Repository gooiman/Gooiman_server, pull requests merged in 2024-09, with the labels that each got.

#3 [setting] 공통적으로 사용할 exception handler, dto 추가, 기본 설정 추가 및 패키지 구조 설정
  gradlew
  src/main/java/dev/gooiman/server/common/controller/HealthCheckController.java
  src/main/java/dev/gooiman/server/common/dto/CommonSuccessDto.java
  src/main/java/dev/gooiman/server/common/dto/ExceptionDto.java
  src/main/java/dev/gooiman/server/common/dto/ResponseDto.java
  src/main/java/dev/gooiman/server/common/exception/ArgumentNotValidExceptionDto.java
  src/main/java/dev/gooiman/server/common/exception/BaseException.java
  src/main/java/dev/gooiman/server/common/exception/BaseResponseStatus.java
  src/main/java/dev/gooiman/server/common/exception/CommonException.java
  src/main/java/dev/gooiman/server/common/exception/ErrorCode.java
  src/main/java/dev/gooiman/server/common/exception/GlobalExceptionHandler.java
  src/main/java/dev/gooiman/server/common/repository/entity/BaseTimeEntity.java
  src/main/java/dev/gooiman/server/config/repository/AuditConfig.java
  src/main/java/dev/gooiman/server/config/web/CorsConfig.java
  src/main/java/dev/gooiman/server/config/web/WebMvcConfig.java
  src/main/java/dev/gooiman/server/controller/TestController.java
  src/main/java/dev/gooiman/server/memo/application/MemoService.java
  src/main/java/dev/gooiman/server/memo/application/dto/CreateMemoResponseDto.java
  src/main/java/dev/gooiman/server/memo/application/dto/MemoSummariseResponseDto.java
  src/main/java/dev/gooiman/server/memo/controller/MemoController.java
  src/main/java/dev/gooiman/server/memo/repository/MemoRepository.java
  src/main/java/dev/gooiman/server/memo/repository/entity/Memo.java
  src/main/java/dev/gooiman/server/model/TestResponse.java
  src/main/java/dev/gooiman/server/page/application/PageService.java
  src/main/java/dev/gooiman/server/page/application/dto/CreatePageResponseDto.java
  src/main/java/dev/gooiman/server/page/controller/PageController.java
  src/main/java/dev/gooiman/server/page/repository/PageRepository.java
  src/main/java/dev/gooiman/server/page/repository/entity/Page.java
  src/main/java/dev/gooiman/server/user/application/dto/LoginRequestDto.java
  src/main/java/dev/gooiman/server/user/controller/UserController.java
  src/main/java/dev/gooiman/server/user/repository/UserRepository.java
  src/main/java/dev/gooiman/server/user/repository/entity/User.java
Labels: :gear: setting

#4 Feat 메모수정
  sql/init.sql
  src/main/java/dev/gooiman/server/common/exception/ErrorCode.java
  src/main/java/dev/gooiman/server/memo/application/MemoService.java
  src/main/java/dev/gooiman/server/memo/application/dto/UpdateMemoRequestDto.java
  src/main/java/dev/gooiman/server/memo/controller/MemoController.java
  src/main/java/dev/gooiman/server/memo/repository/entity/Memo.java
  src/main/java/dev/gooiman/server/page/repository/entity/Page.java
  src/main/java/dev/gooiman/server/user/application/UserService.java
  src/main/java/dev/gooiman/server/user/repository/UserRepository.java
  src/main/java/dev/gooiman/server/user/repository/entity/User.java
Labels: :sparkles: feat, :hammer_and_wrench: refactor

#5 feat: 메모 삭제
  src/main/java/dev/gooiman/server/memo/application/MemoService.java
  src/main/java/dev/gooiman/server/memo/controller/MemoController.java
Labels: :sparkles: feat

#7 feat 메모 생성
  sql/init.sql
  src/main/java/dev/gooiman/server/common/dto/CommonIdResponseDto.java
  src/main/java/dev/gooiman/server/common/exception/ErrorCode.java
  src/main/java/dev/gooiman/server/memo/application/MemoService.java
  src/main/java/dev/gooiman/server/memo/application/dto/CreateMemoRequestDto.java
  src/main/java/dev/gooiman/server/memo/controller/MemoController.java
  src/main/java/dev/gooiman/server/page/application/PageService.java
Labels: :sparkles: feat

#10 [feat] 메모 목록
  src/main/java/dev/gooiman/server/memo/application/MemoService.java
  src/main/java/dev/gooiman/server/memo/application/dto/MemoDto.java
  src/main/java/dev/gooiman/server/memo/controller/MemoController.java
  src/main/java/dev/gooiman/server/memo/repository/MemoRepository.java
Labels: :sparkles: feat

#11 Feat 메모열람
  src/main/java/dev/gooiman/server/memo/application/MemoService.java
  src/main/java/dev/gooiman/server/memo/application/dto/GetMemoResponseDto.java
  src/main/java/dev/gooiman/server/memo/controller/MemoController.java
  src/main/java/dev/gooiman/server/memo/repository/entity/Memo.java
Labels: :sparkles: feat

#13 feat: swagger 설정
  src/main/java/dev/gooiman/server/config/web/SwaggerConfig.java
  src/main/resources/application.yml
Labels: :scroll: docs

#24 [Setting] security 설정
  Dockerfile
  build.gradle.kts
  src/main/java/dev/gooiman/server/common/exception/ErrorCode.java
  src/main/java/dev/gooiman/server/config/security/JwtConfig.java
  src/main/java/dev/gooiman/server/config/security/PasswordConfig.java
  src/main/java/dev/gooiman/server/config/security/SecurityConfig.java
  src/main/java/dev/gooiman/server/config/web/WebMvcConfig.java
  src/main/java/dev/gooiman/server/memo/application/dto/CreateMemoRequestDto.java
  src/main/java/dev/gooiman/server/page/application/PageService.java
  src/main/java/dev/gooiman/server/security/application/CustomAuthenticationService.java
  src/main/java/dev/gooiman/server/security/application/CustomUserDetailsService.java
  src/main/java/dev/gooiman/server/security/application/JwtAuthenticationService.java
  src/main/java/dev/gooiman/server/security/application/dto/JwtResponseDto.java
  src/main/java/dev/gooiman/server/security/application/dto/LoginRequestDto.java
  src/main/java/dev/gooiman/server/security/controller/AuthenticationController.java
  src/main/java/dev/gooiman/server/security/exception/entrypoint/JwtAuthenticationEntryPoint.java
  src/main/java/dev/gooiman/server/security/exception/handler/JwtAccessDeniedHandler.java
  src/main/java/dev/gooiman/server/security/fliter/JwtFilter.java
  src/main/java/dev/gooiman/server/security/provider/CustomAuthenticationProvider.java
  src/main/java/dev/gooiman/server/security/provider/JwtAuthenticationProvider.java
  src/main/java/dev/gooiman/server/security/repository/entity/CustomUserDetails.java
  src/main/java/dev/gooiman/server/security/resolver/JwtAuthorizationArgumentResolver.java
  src/main/java/dev/gooiman/server/security/resolver/Login.java
  src/main/java/dev/gooiman/server/user/application/dto/LoginRequestDto.java
  src/main/java/dev/gooiman/server/user/repository/UserRepository.java
  src/main/java/dev/gooiman/server/user/repository/entity/User.java
  src/main/resources/application.yml
Labels: :gear: setting

#31 feat: 프로덕션 환경 배포 설정
  .github/workflows/publish-prod.yml
  codedeploy/prod/appspec.yml
  codedeploy/prod/docker-compose.yml
  main.tf
  src/main/resources/application-prod.yml
Labels: :sparkles: feat

#34 setting: swagger security 설정
  docker-compose.bootrun.yml
  src/main/java/dev/gooiman/server/auth/controller/AuthController.java
  src/main/java/dev/gooiman/server/config/web/SwaggerConfig.java
  src/main/java/dev/gooiman/server/page/controller/PageController.java
Labels: :gear: setting

#36 fix: `GET /api/page/{pageId}`, 메모 CUD API 수정
  src/main/java/dev/gooiman/server/auth/application/UserService.java
  src/main/java/dev/gooiman/server/memo/application/MemoService.java
  src/main/java/dev/gooiman/server/memo/repository/MemoRepository.java
  src/main/java/dev/gooiman/server/memo/repository/entity/Memo.java
Labels: :lady_beetle: bug
